import {Candidate} from "./candidate";
export const CANDIDATES: Candidate[] = [
  {
    id: 1,
    name: 'Maciej',
    surname: 'Wawryszuk',
    email: 'dupa1234@gmail.com',
    phone: '+48123456789',
    date: '01/01/01',
    cv: 'tak',
    position: 'Junior Angular Developer',
    experience: 1,
    category: 'FrontEnd',
    language: 'Angular',
    availability: 'Natychmiast',
    adopted: 'Przyjęty',
  },
  {
    id: 2,
    name: 'Michał',
    surname: 'Zrol',
    email: 'dupwqeewa1234@gmail.com',
    phone: '+48323456789',
    date: '02/01/01',
    cv: 'tak',
    position: 'Mid Java Developer',
    experience: 3,
    category: 'Backend',
    language: 'Java',
    availability: 'Za 2 miesiące',
    adopted: 'Przyjęty',
  },  {
    id: 3,
    name: 'Przemek',
    surname: 'Kidzyn',
    email: 'kdz1334@gmail.com',
    phone: '+48124565789',
    date: '03/03/03',
    cv: 'tak',
    position: 'Junior React Developer',
    experience: 0,
    category: 'FrontEnd',
    language: 'React',
    availability: 'Natychmiast',
    adopted: 'Nie Przyjęty',
  },
  {
    id: 4,
    name: 'Łukasz',
    surname: 'Polańczyk',
    email: 'dupa1234@gmail.com',
    phone: '+48123456789',
    date: '01/01/01',
    cv: 'tak',
    position: 'Senior Python Developer',
    experience: 7,
    category: 'Backend',
    language: 'Python',
    availability: 'Natychmiast',
    adopted: 'Przyjęty',
  },

];
